# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kvname-system-msi-{{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" 
    userAssignedIdentityID: {{ .Values.keyVault.userAssignedIdentityID }}
    keyvaultName: {{ .Values.keyVault.name }}
    cloudName: "AzurePublicCloud" 
    objects:  |
      array:
        {{- range .Values.vaultSecrets }}
        - |
          objectName: {{ .objectName }}
          objectType: secret        
          objectVersion: ""
    tenantId: {{ .Values.keyVault.tenantId }}
  secretObjects:
  - secretName: {{ .Chart.Name }}-secret
    type: Opaque
    data:
      {{- range .Values.vaultSecrets }}
      - objectName: {{ .objectName }}
        key: {{ .objectName }}
      {{- end }}