replicaCount: 1
namespace: base-platform

image:
  repositoryName: lahiru1029/analytics-service-develop
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

livenessProbe:
  enabled: false
  httpGetPath: /v1/health/live
readinessProbe:
  enabled: false
  httpGetPath: /v1/health/ready


resources: 
  limits:
    cpu: 200m
    memory: 400Mi
  requests:
    cpu: 200m
    memory: 400Mi

# tolerations:
#   - key: "taint"
#     operator: "Equal"
#     value: "iit"
#     effect: "NoSchedule"

#   - key: "kubernetes.azure.com/scalesetpriority"
#     operator: "Equal"
#     value: "spot"
#     effect: "NoSchedule"

# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: "taint"
#               operator: "In"
#               values:
#                 - "iit"
#             - key: "kubernetes.azure.com/scalesetpriority"
#               operator: "In"
#               values:
#                 - "spot"